client_id = "bfb33fe92c4274f1ba39275effdb6c25"
name = "Triple-Luxe-Sections"
application_url = "https://triple-luxe-sections-1.onrender.com"
embedded = true
handle = "triple-luxe-sections"

[webhooks]
api_version = "2025-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://triple-luxe-sections-1.onrender.com/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "https://triple-luxe-sections-1.onrender.com/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://triple-luxe-sections-1.onrender.com/webhooks/compliance"

[access_scopes]
scopes = "read_products,write_products,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://triple-luxe-sections-1.onrender.com/auth/callback",
  "https://triple-luxe-sections-1.onrender.com/auth/login"
]
