# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bfb33fe92c4274f1ba39275effdb6c25"
name = "Triple-Luxe-Sections"
application_url = "https://lonely-weed-sep-publisher.trycloudflare.com"
embedded = true
handle = "triple-luxe-sections"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://inter-forgot-consolidated-occupied.trycloudflare.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://inter-forgot-consolidated-occupied.trycloudflare.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://lonely-weed-sep-publisher.trycloudflare.com/auth/callback", "https://lonely-weed-sep-publisher.trycloudflare.com/auth/shopify/callback", "https://lonely-weed-sep-publisher.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
