# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bfb33fe92c4274f1ba39275effdb6c25"
name = "Triple-Luxe-Sections"
application_url = "https://triple-luxe-sections-1.onrender.com/app"
embedded = true
handle = "triple-luxe-sections"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://inter-forgot-consolidated-occupied.trycloudflare.com/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://inter-forgot-consolidated-occupied.trycloudflare.com/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://triple-luxe-sections-1.onrender.com/auth/callback",
  "https://triple-luxe-sections-1.onrender.com/auth/login"
]

[pos]
embedded = false
